------------------------------------------统计管理------------------------------------------
ALTER TABLE "CF_STATISTIC_FILTER" DROP CONSTRAINT "fk_CF_STATISTIC_FILTER";
ALTER TABLE "CF_STATISTIC_CHART" DROP CONSTRAINT "fk_CF_STATISTIC_CHART";
ALTER TABLE "CF_STATISTIC_CHART" DROP CONSTRAINT "fk_CF_STATISTIC_CHART_1";
ALTER TABLE "CF_CHART_INSTANCE" DROP CONSTRAINT "fk_CF_CHART_INSTANCE";

DROP TABLE "CF_STATISCTIC";
DROP TABLE "CF_STATISTIC_FILTER";
DROP TABLE "CF_STATISTIC_CHART";
DROP TABLE "CF_CHART_TYPE";
DROP TABLE "CF_CHART_INSTANCE";

DROP SEQUENCE SEQ_CF_CHART_INSTANCE;
DROP SEQUENCE SEQ_CF_CHART_TYPE;
DROP SEQUENCE SEQ_CF_STATISCTIC;
DROP SEQUENCE SEQ_CF_STATISTIC_CHART;
DROP SEQUENCE SEQ_CF_STATISTIC_FILTER;

CREATE TABLE CF_CHART_INSTANCE
(
    ID INTEGER PRIMARY KEY NOT NULL,
    CF_CHART_TYPE_ID INTEGER,
    NAME VARCHAR2(255),
    HANDLER VARCHAR2(255)
);

CREATE TABLE CF_CHART_TYPE
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR2(255)
);

CREATE TABLE CF_STATISCTIC
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR2(200),
    SQL VARCHAR2(4000)
);

CREATE TABLE CF_STATISTIC_CHART
(
    ID INTEGER PRIMARY KEY NOT NULL,
    CF_STATISTIC_ID INTEGER,
    CF_CHART_INSTANCE_ID INTEGER,
    CUSTOM_HANDLER VARCHAR2(255),
    TITLE VARCHAR2(255),
    PRE_PROCESSOR VARCHAR2(255)
);


CREATE TABLE CF_STATISTIC_FILTER
(
    ID INTEGER PRIMARY KEY NOT NULL,
    COLUMN_ID INTEGER,
    CF_STATISTIC_ID INTEGER
);


CREATE SEQUENCE SEQ_CF_CHART_INSTANCE INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CF_CHART_TYPE INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CF_STATISCTIC INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CF_STATISTIC_CHART INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CF_STATISTIC_FILTER INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;

ALTER TABLE CF_CHART_INSTANCE ADD FOREIGN KEY (CF_CHART_TYPE_ID) REFERENCES CF_CHART_TYPE (ID);
ALTER TABLE CF_STATISTIC_CHART ADD FOREIGN KEY (CF_CHART_INSTANCE_ID) REFERENCES CF_CHART_INSTANCE (ID);
ALTER TABLE CF_STATISTIC_CHART ADD FOREIGN KEY (CF_STATISTIC_ID) REFERENCES CF_STATISCTIC (ID);
ALTER TABLE CF_STATISTIC_FILTER ADD FOREIGN KEY (CF_STATISTIC_ID) REFERENCES CF_STATISCTIC (ID);


INSERT INTO CWM_SYS_FUNCTION (FUNCTIONID, CODE, NAME, PARENTID, URL, NOTES, ADD_FLG, DEL_FLG, EDIT_FLG, POSITION, LOGTYPE, LOGSHOW, IS_SHOW, TBOM_FLG, JS, ICON) VALUES (961, 'F_STATISTIC', '统计管理配置', 106, null, null, '1', '1', '1', 5, null, null, 1, '0', null, 'app/images/function/表单管理.png');
INSERT INTO CWM_SYS_FUNCTION (FUNCTIONID, CODE, NAME, PARENTID, URL, NOTES, ADD_FLG, DEL_FLG, EDIT_FLG, POSITION, LOGTYPE, LOGSHOW, IS_SHOW, TBOM_FLG, JS, ICON) VALUES (1020, 'F_STASTISTIC_CHART_SETUP', '统计图形设置', 961, null, null, '1', '1', '1', 1, null, null, 1, '0', 'OrientTdm.BackgroundMgr.Statistic.ChartConfig.ChartConfigMainPanel', 'app/images/function/表单管理.png');
INSERT INTO CWM_SYS_FUNCTION (FUNCTIONID, CODE, NAME, PARENTID, URL, NOTES, ADD_FLG, DEL_FLG, EDIT_FLG, POSITION, LOGTYPE, LOGSHOW, IS_SHOW, TBOM_FLG, JS, ICON) VALUES (1021, 'F_STATISTIC_SETUP', '统计设置', 961, null, null, '1', '1', '1', 2, null, null, 1, '0', 'OrientTdm.BackgroundMgr.Statistic.Setup.StatisticSetUpDashBoard', 'app/images/function/表单管理.png');


INSERT INTO CF_CHART_TYPE (ID, NAME) VALUES (160, '柱状图');
INSERT INTO CF_CHART_TYPE (ID, NAME) VALUES (180, '饼状图');
INSERT INTO CF_STATISCTIC (ID, NAME, SQL) VALUES (180, '项目状态统计', 'select ID,STATUS_341 status from CB_PROJECT_240 where 1=1');
INSERT INTO CF_STATISCTIC (ID, NAME, SQL) VALUES (200, '日志统计', 'SELECT * FROM CWM_SYS_LOG WHERE OP_DATE >=TRUNC(SYSDATE-7) ORDER BY ID');
INSERT INTO CF_CHART_INSTANCE (ID, CF_CHART_TYPE_ID, NAME, HANDLER) VALUES (160, 180, '默认饼状图', 'OrientTdm.BackgroundMgr.Statistic.Chart.Default.Bar.EChartPiePanel');
INSERT INTO CF_CHART_INSTANCE (ID, CF_CHART_TYPE_ID, NAME, HANDLER) VALUES (180, 160, '默认柱状图', 'OrientTdm.BackgroundMgr.Statistic.Chart.Default.Bar.EChartBarPanel');
INSERT INTO CF_STATISTIC_CHART (ID, CF_STATISTIC_ID, CF_CHART_INSTANCE_ID, CUSTOM_HANDLER, TITLE, PRE_PROCESSOR) VALUES (140, 180, 160, null, '项目状态统计', 'projectStatusStatisticPreProcesser');
INSERT INTO CF_STATISTIC_CHART (ID, CF_STATISTIC_ID, CF_CHART_INSTANCE_ID, CUSTOM_HANDLER, TITLE, PRE_PROCESSOR) VALUES (200, 200, 180, null, '最近一周操作统计', 'logRecentOperatStatisticBarPreProcesser');


------------------------------------------TBom树------------------------------------------
ALTER TABLE "CWM_TBOM" ADD ("EXPAND_LEVEL" VARCHAR2(10) NULL);

------------------------------------------部门------------------------------------------
ALTER TABLE "CWM_SYS_DEPARTMENT" ADD ("ORDERS" NUMBER(38) NULL);

------------------------------------------采集集成------------------------------------------
CREATE TABLE CF_QUANTITY
(
    ID NUMBER PRIMARY KEY NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    DATATYPE VARCHAR2(100) NOT NULL,
    UNIT_ID NUMBER NOT NULL
);

CREATE TABLE CF_QUANTITY_TEMPLATE_RELATION
(
    ID NUMBER PRIMARY KEY NOT NULL,
    TEMPLATE_ID NUMBER NOT NULL,
    QUANTITY_ID NUMBER NOT NULL
);

CREATE TABLE CF_QUANTITY_TEMPLATE
(
    ID NUMBER PRIMARY KEY NOT NULL,
    NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE CF_QUANTITY_INSTANCE
(
    ID NUMBER PRIMARY KEY NOT NULL,
    QUANTITY_ID NUMBER NOT NULL,
    MODEL_ID NUMBER NOT NULL,
    DATA_ID NUMBER NOT NULL,
    UNIT_ID NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_CF_QUANTITY INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CF_QUANTITY_TR INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CF_QUANTITY_TEMPLATE INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_QUANTITY_INSTANCE INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_NUMBERUNIT INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;

INSERT INTO COLLAB_FUNCTION (ID, NAME, PAR_FUNCTION_ID, BELONGED_MODEL, COMMENT_INFO, DISPLAY_ORDER, ICON_CLS) VALUES ('21', '采集数据', null, 'CB_TASK', null, '1', 'icon-measurement');

INSERT INTO CWM_SYS_FUNCTION (FUNCTIONID, CODE, NAME, PARENTID, URL, NOTES, ADD_FLG, DEL_FLG, EDIT_FLG, POSITION, LOGTYPE, LOGSHOW, IS_SHOW, TBOM_FLG, JS, ICON) VALUES (1060, 'F_MEASURE', '采集数据配置', 106, null, null, '1', '1', '1', 3, null, null, 1, '0', null, 'app/images/function/表单管理.png');
INSERT INTO CWM_SYS_FUNCTION (FUNCTIONID, CODE, NAME, PARENTID, URL, NOTES, ADD_FLG, DEL_FLG, EDIT_FLG, POSITION, LOGTYPE, LOGSHOW, IS_SHOW, TBOM_FLG, JS, ICON) VALUES (1061, 'F_MEASURE_META', '采集变量管理', 1060, null, null, '1', '1', '1', 1, null, null, 1, '0', 'OrientTdm.BackgroundMgr.Quantity.Meta.QuantityDashBord', 'app/images/function/表单管理.png');
INSERT INTO CWM_SYS_FUNCTION (FUNCTIONID, CODE, NAME, PARENTID, URL, NOTES, ADD_FLG, DEL_FLG, EDIT_FLG, POSITION, LOGTYPE, LOGSHOW, IS_SHOW, TBOM_FLG, JS, ICON) VALUES (1062, 'F_MM_TEMPLATE', '采集模板管理', 1060, null, null, '1', '1', '1', 2, null, null, 1, '0', 'OrientTdm.BackgroundMgr.Quantity.Template.QuantityTemplateDashBord', 'app/images/function/表单管理.png');
INSERT INTO CWM_SYS_FUNCTION (FUNCTIONID, CODE, NAME, PARENTID, URL, NOTES, ADD_FLG, DEL_FLG, EDIT_FLG, POSITION, LOGTYPE, LOGSHOW, IS_SHOW, TBOM_FLG, JS, ICON) VALUES (1080, 'F_SCHEMA_DATA', '数据模型', 8, null, null, '1', '1', '1', 1, null, null, 1, '0', 'OrientTdm.DataMgr.SchemaData.SchemaDataDashBord', 'app/images/function/表单管理.png');

------------------------------------------任务代办------------------------------------------
CREATE TABLE FLOW_COMMISSION
(
    ID VARCHAR2(38) PRIMARY KEY NOT NULL,
    PDID VARCHAR2(100) NOT NULL,
    MAIN_USER_NAME VARCHAR2(38) NOT NULL,
    SLAVE_USER_NAME VARCHAR2(38) NOT NULL
);
CREATE SEQUENCE SEQ_FLOW_COMMISSION INCREMENT BY 1 START WITH 500 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;

INSERT INTO "CWM_SYS_FUNCTION" ("FUNCTIONID", "CODE", "NAME", "PARENTID", "URL", "NOTES", "ADD_FLG", "DEL_FLG", "EDIT_FLG", "POSITION", "LOGTYPE", "LOGSHOW", "IS_SHOW", "TBOM_FLG", "JS", "ICON") VALUES ('1100', 'FlowCommission', '审批流程代办', '980', NULL, NULL, '1', '1', '1', '3', NULL, NULL, '1', '0', 'OrientTdm.BackgroundMgr.FlowCommission.FlowCommissionDashBord', 'app/images/function/角色.png');



-------------------------- collab ------------------------------
CREATE TABLE "CB_SYS_NODE_DEPEND" ( "ID" VARCHAR2(38 BYTE) NOT NULL , "NODE_ID" VARCHAR2(38 BYTE) NULL , "NODE_VERSION" NUMBER NULL , "DEPEND_ID" VARCHAR2(38 BYTE) NULL , "DEPEND_VERSION" NUMBER NULL , "P_ID" VARCHAR2(38 BYTE) NULL , "P_VERSION" NUMBER NULL );
CREATE SEQUENCE SEQ_CB_SYS_NODE_DEPEND;

ALTER TABLE "CB_SYS_NODE" RENAME COLUMN "BUSINESSMODEL_ID" TO "BM_DATA_ID";
ALTER TABLE "CB_SYS_NODE_HIS" RENAME COLUMN "BUSINESSMODEL_ID" TO "BM_DATA_ID";

ALTER TABLE "CWM_MSG" ADD ( "DATA" VARCHAR2(3000) NULL  ) ;

--------------------------------2018/10/30  by gny-----------------------
ALTER TABLE "CWM_DATAOBJECT" ADD ( "ORIGINAL_OBJ_ID" VARCHAR2(38) ) ;
ALTER TABLE "CWM_DATAOBJECT_OLDVERSION" ADD ( "ORIGINAL_OBJ_ID" VARCHAR2(38) ) ;



