CREATE TABLE ALARM_INFO
(
  ID         VARCHAR2(30 CHAR),
  NLEVEL     NUMBER(2),
  CLASSNAME  VARCHAR2(100 CHAR),
  PARAMS     VARCHAR2(500 CHAR),
  ISALARM    NUMBER(1)                          DEFAULT 0
);

CREATE TABLE ALARM_CONTENT
(
  ID             VARCHAR2(300 CHAR),
  TITLE          VARCHAR2(200 CHAR),
  URL            VARCHAR2(200 BYTE),
  ALARM_INFO_ID  VARCHAR2(30 CHAR),
  CONTENT        CLOB
);
 
CREATE TABLE ALARM_NOTICE
(
  ID             VARCHAR2(30 CHAR),
  NOTICETYPE     NUMBER(8),
  TRIGGERTYPE    VARCHAR2(1 BYTE),
  INTERVAL       INTEGER,
  REPEAT         INTEGER,
  YEAR           VARCHAR2(4 BYTE),
  MONTH          VARCHAR2(2 BYTE),
  WEEKDAY        VARCHAR2(1 BYTE),
  TIME           VARCHAR2(10 BYTE),
  ALARM_INFO_ID  VARCHAR2(30 CHAR),
  MONTHDAY       VARCHAR2(2 BYTE)
);


CREATE TABLE ALARM_USER
(
  ALARMID  VARCHAR2(30 CHAR),
  USERID   VARCHAR2(30 CHAR),
  TYPE     NUMBER(1)
);


CREATE TABLE ALARM_INFO_HIST
(
  ID        VARCHAR2(30 CHAR),
  NLEVEL    NUMBER(10),
  TITLE     VARCHAR2(200 CHAR),
  URL       VARCHAR2(200 BYTE),
  SENDTIME  DATE,
  CONTENT   CLOB
);

CREATE TABLE ALARM_USER_HIST
(
  ALARMID  VARCHAR2(30 CHAR),
  USERID   VARCHAR2(30 CHAR),
  TYPE     NUMBER(1)
);


ALTER TABLE ALARM_INFO ADD (
  CONSTRAINT ALARM_INFO_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ALARM_CONTENT ADD (
  CONSTRAINT PK_CONTENT
 PRIMARY KEY
 (ID));
 
ALTER TABLE ALARM_CONTENT ADD (
  CONSTRAINT FK_CONTENT_INFO 
 FOREIGN KEY (ALARM_INFO_ID) 
 REFERENCES ALARM_INFO (ID));

 ALTER TABLE ALARM_CONTENT ADD (
  CONSTRAINT UN_CONTENT_INFO
 UNIQUE (ALARM_INFO_ID));
 
 ALTER TABLE ALARM_NOTICE ADD (
  PRIMARY KEY
 (ID));
 
 ALTER TABLE ALARM_NOTICE ADD (
  CONSTRAINT FK_NOTICE_INFO 
 FOREIGN KEY (ALARM_INFO_ID) 
 REFERENCES ALARM_INFO (ID));
 
 ALTER TABLE ALARM_NOTICE ADD (
  CONSTRAINT UN_NOTICE_INFO
 UNIQUE (ALARM_INFO_ID));
 
 ALTER TABLE ALARM_USER ADD (
  CONSTRAINT ALARM_USER_PK
 PRIMARY KEY
 (USERID, ALARMID));
 
 ALTER TABLE ALARM_USER ADD (
  CONSTRAINT FK_CWM_SYS_USER 
 FOREIGN KEY (USERID) 
 REFERENCES CWM_SYS_USER (ID));

 ALTER TABLE ALARM_USER ADD (
  CONSTRAINT FK_USER_INFO 
 FOREIGN KEY (ALARMID) 
 REFERENCES ALARM_INFO (ID));
 
ALTER TABLE ALARM_INFO_HIST ADD (
  CONSTRAINT ALARM_INFO_HIST_PK
 PRIMARY KEY
 (ID));
 
 ALTER TABLE ALARM_USER_HIST ADD (
  CONSTRAINT ALARM_USER_HIST_PK
 PRIMARY KEY
 (USERID, ALARMID));
 
 ALTER TABLE ALARM_USER_HIST ADD (
  CONSTRAINT FK_CWM_SYS_USER_HIST 
 FOREIGN KEY (USERID) 
 REFERENCES CWM_SYS_USER (ID));
 
 ALTER TABLE ALARM_USER_HIST ADD (
  CONSTRAINT FK_USER_INFO_HIST 
 FOREIGN KEY (ALARMID) 
 REFERENCES ALARM_INFO_HIST (ID));
 
 
 CREATE SEQUENCE SEQ_ALARM_INFO
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE SEQUENCE SEQ_ALARM_USER
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE SEQUENCE SEQ_ALARM_CONTENT
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;  
  
CREATE SEQUENCE SEQ_ALARM_NOTICE
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER; 
  
CREATE SEQUENCE SEQ_ALARM_INFO_HIST
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER; 

CREATE SEQUENCE SEQ_ALARM_USER_HIST
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER; 