drop table FLOW_DATA_RELATION;
DROP table TASK_DATA_RELATION;
DROP table HIST_FLOW_DATA_RELATION;
DROP TABLE HIST_TASK_DATA_RELATION;
DROP table COLLAB_ROLE_FUNCTION;
DROP table COLLAB_ROLE_USER;
DROP table COLLAB_ROLE;
DROP table COLLAB_FUNCTION;
DROP table DATA_FLOW_REL_SETTING;
DROP table NOTICE;
DROP table COLLAB_TEMPLATE;

--流程数据关系表
CREATE TABLE FLOW_DATA_RELATION (
	ID VARCHAR2(20) NOT NULL, -- 自增主键
	MAIN_TYPE VARCHAR2(30) NOT NULL, --流程的主类型，如协同流程&审批流程
	SUB_TYPE VARCHAR2(30), --流程的子类型，如wbs审批流程、模型数据审批
	TABLE_NAME VARCHAR2(30) NOT NULL, --普通表则为表名，DS表则为MODEL_NAME
	DATA_ID VARCHAR2(20) NOT NULL, --对应的数据ID
	PI_ID VARCHAR2(50), --对应的流程实例ID
	EXTRAM_PARAMS VARCHAR2(400), --对应的流程实例ID
	CREATE_TIME TIMESTAMP(6), --创建时间
	STRATEGY VARCHAR2(200),--绑定的策略，以逗号分隔
	constraint PK_FLOW_DATA_RELATION primary key (ID)
);

--任务数据关系表
CREATE TABLE TASK_DATA_RELATION (
	ID VARCHAR2(20) NOT NULL, --自增主键
	TYPE VARCHAR2(30), --任务类型
	TABLE_NAME VARCHAR2(30), --普通表则为表名，DS表则为MODEL_NAME
	DATA_ID VARCHAR2(20), --对应的数据ID
  PI_ID VARCHAR2(50), --对应的流程实例ID
	TASK_NAME VARCHAR2(50), --对应的任务名称
	CREATE_TIME TIMESTAMP(6),--创建时间
	STRATEGY VARCHAR2(200),--绑定的策略，以逗号分隔
	constraint PK_TASK_DATA_RELATION primary key (ID)
);

--历史流程数据关系表
CREATE TABLE HIST_FLOW_DATA_RELATION (
	ID VARCHAR2(20) NOT NULL, -- 自增主键
	MAIN_TYPE VARCHAR2(30) NOT NULL, --流程的主类型，如协同流程&审批流程
	SUB_TYPE VARCHAR2(30), --流程的子类型，如wbs审批流程、模型数据审批
	TABLE_NAME VARCHAR2(30) NOT NULL, --普通表则为表名，DS表则为MODEL_NAME
	DATA BLOB, --绑定的数据的序列化信息（对数据表）或字节信息（文件等）
	HIST_PI_ID VARCHAR2(50), --绑定的历史流程ID
	EXTRAM_PARAMS VARCHAR2(400), --对应的流程实例ID
	STRATEGY VARCHAR2(200),--绑定的策略
	constraint PK_HIST_FLOW_DATA_RELATION primary key (ID)
);

--历史任务数据关系表
CREATE TABLE HIST_TASK_DATA_RELATION (
	ID VARCHAR2(20) NOT NULL,   -- 自增主键
	TYPE VARCHAR2(30), --任务类型
	TABLE_NAME VARCHAR2(30), --普通表则为表名，DS表则为MODEL_NAME
	DATA BLOB, --绑定的数据的序列化信息（对数据表）或字节信息（文件等）
	HIST_TASK_ID VARCHAR2(50), --绑定的历史任务ID
	STRATEGY VARCHAR2(200), --绑定的策略
	constraint PK_HIST_TASK_DATA_RELATION primary key (ID)
);

--角色信息表
CREATE TABLE COLLAB_ROLE (
	ID VARCHAR2(20) NOT NULL,   -- 自增主键
	NAME VARCHAR2(30), --角色名称
	MODEL_NAME VARCHAR2(30), --该角色对应的模型英文名
	DATA_ID VARCHAR2(30), --该角色对应的模型数据ID
	constraint PK_COLLAB_ROLE primary key (ID)
);

--功能点信息表
CREATE TABLE COLLAB_FUNCTION (
	ID VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(30),
	PAR_FUNCTION_ID VARCHAR2(20),
	BELONGED_MODEL VARCHAR2(30),
  COMMENT_INFO VARCHAR2(300),
  DISPLAY_ORDER VARCHAR2(20) DEFAULT 0,
	CONSTRAINT PK_COLLAB_FUNCTION primary key (ID)
);

alter table COLLAB_FUNCTION
   add constraint FK_PAR_FUNCTION_ID foreign key (PAR_FUNCTION_ID)
      references COLLAB_FUNCTION (ID);

--角色与功能点多对多关系存储表
CREATE TABLE COLLAB_ROLE_FUNCTION (
	ROLE_ID VARCHAR2(20),
	FUNCTION_ID VARCHAR2(20),
	constraint PK_COLLAB_ROLE_FUNCTION primary key (ROLE_ID, FUNCTION_ID)
);

alter table COLLAB_ROLE_FUNCTION
   add constraint FK_ROLE_ID foreign key (ROLE_ID)
      references COLLAB_ROLE (ID);

alter table COLLAB_ROLE_FUNCTION
   add constraint FK_FUNCTION_ID foreign key (FUNCTION_ID)
      references COLLAB_FUNCTION (ID);

--角色与用户多对多关系存储表
CREATE TABLE COLLAB_ROLE_USER (
	ROLE_ID VARCHAR2(20),
	USER_ID VARCHAR2(20),
	constraint PK_COLLAB_ROLE_USER primary key (ROLE_ID, USER_ID)
);

alter table COLLAB_ROLE_USER
   add constraint FK_ROLE_USER_ROLE_ID foreign key (ROLE_ID)
      references COLLAB_ROLE (ID);

alter table COLLAB_ROLE_USER
   add constraint FK_ROLE_USER_USER_ID foreign key (USER_ID)
      references CWM_SYS_USER (ID);

--数据上下游关系表
CREATE TABLE DATA_FLOW_REL_SETTING (
	ID VARCHAR2(20) NOT NULL,
	MODEL_NAME VARCHAR2(20),
	DATA_ID VARCHAR2(20),
	UPPER_DATA_ID VARCHAR2(20),
	constraint PK_DATA_FLOW_REL_SETTING primary key (ID)
);

--通知表
CREATE TABLE NOTICE (
	ID VARCHAR2(20) NOT NULL,
	SUBJECT VARCHAR2(20),
	SENDER_ID VARCHAR2(20),
	RECERVER_ID VARCHAR2(20),
	SEND_TIME TIMESTAMP,
	CONTENT VARCHAR(2000),
	STAR NUMBER(1) DEFAULT 0,
	STATUS VARCHAR2(20),
	constraint PK_NOTICE primary key (ID)
);

alter table NOTICE
   add constraint FK_SENDER_ID foreign key (SENDER_ID)
      references CWM_SYS_USER (ID);

alter table NOTICE
   add constraint FK_RECERVER_ID foreign key (RECERVER_ID)
      references CWM_SYS_USER (ID);

--模板表
CREATE TABLE COLLAB_TEMPLATE (
	ID VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(20),
	VERSION VARCHAR2(20),
	TYPE VARCHAR2(20),
	EXPORT_TIME TIMESTAMP,
	EXPORT_USER_ID VARCHAR(20),
	IS_PRIVATE NUMBER(1) DEFAULT 0,
	AUDIT_USER_ID VARCHAR2(20),
	TEMPLATE BLOB,
	constraint PK_COLLAB_TEMPLATE primary key (ID)
);

alter table COLLAB_TEMPLATE
   add constraint FK_EXPORT_USER_ID foreign key (EXPORT_USER_ID)
      references CWM_SYS_USER (ID);

alter table COLLAB_TEMPLATE
   add constraint FK_AUDIT_USER_ID foreign key (AUDIT_USER_ID)
      references CWM_SYS_USER (ID);




--协同父子流程关系表
CREATE TABLE COLLAB_FLOW_RELATION (
	ID VARCHAR2(20) NOT NULL, --自增主键
	PARENT_PI_ID VARCHAR2(50), --父pi
	SUB_PI_ID VARCHAR2(50), --子pi
  TASK_ID VARCHAR2(20), --对应的collab task id
	constraint PK_COLLAB_FLOW_RELATION primary key (ID)
);


--协同数据流程表
CREATE TABLE COLLAB_DATA_FLOW(
  ID VARCHAR2(20) NOT NULL, --自增主键
  MODELID VARCHAR2(50) NOT NULL, --业务模型的ID
  SRCID VARCHAR2(50) NOT NULL,  --数据流开始节点ID
  DESTNYID VARCHAR2(50) NOT NULL,  --数据流结束节点ID
	constraint PK_COLLAB_DATA_FLOW primary key (ID)
)

--数据流定义的Task 的位置信息
CREATE TABLE COLLAB_JOB_CARVEPOS(
  ID VARCHAR2(20) NOT NULL, --自增主键
  MODELID VARCHAR2(50) NOT NULL, --业务模型的ID
  DATAID VARCHAR2(50) NOT NULL,  --数据流的节点ID
  XPOS VARCHAR2(50) NOT NULL,  --数据流节点的X位置
  YPOS VARCHAR2(50) NOT NULL,  --数据流节点的Y位置
  WIDTH VARCHAR2(50) NOT NULL,  --数据流节点的宽度
  HEIGTH VARCHAR2(50) NOT NULL,  --数据流节点的高度
	constraint COLLAB_JOB_CARVEPOS primary key (ID)
)

--数据流任务信息
CREATE TABLE COLLAB_DATATASK(
  ID VARCHAR2(20) NOT NULL, --自增主键
  TASKMODELID VARCHAR2(50) NOT NULL, --业务模型的ID
  DATAID VARCHAR2(50) NOT NULL,  --数据流的节点ID
  USERID VARCHAR2(50) NOT NULL,  --用户ID
  TASKSTATE  VARCHAR2(50) NOT NULL,  --用户ID
  CREATETIME      TIMESTAMP(6),--创建时间
  TAKETIME        TIMESTAMP(6),--领取时间
  FINISHTIME      TIMESTAMP(6),--完成事件
  MESSAGE  VARCHAR2(500) ,  --任务详情
	constraint COLLAB_DATATASK primary key (ID)
)

--数据流任务信息历史表
CREATE TABLE COLLAB_DATATASK_HIS(
  ID VARCHAR2(20) NOT NULL, --自增主键
  TASKMODELID VARCHAR2(50) NOT NULL, --业务模型的ID
  DATAID VARCHAR2(50) NOT NULL,  --数据流的节点ID
  USERID VARCHAR2(50) NOT NULL,  --用户ID
  TASKSTATE  VARCHAR2(50) NOT NULL,  --用户ID
  CREATETIME      TIMESTAMP(6),--创建时间
  TAKETIME        TIMESTAMP(6),--领取时间
  FINISHTIME      TIMESTAMP(6),--完成事件
  MESSAGE         VARCHAR2(500),--任务详情
	constraint COLLAB_DATATASK_HIS primary key (ID)
)

--修改
alter table FLOW_DATA_RELATION add (EXTRAM_PARAMS VARCHAR2(400));


--項目模型關係表
CREATE TABLE COLLAB_PRJ_MODEL_RELATION (
	ID VARCHAR2(20) NOT NULL, -- 自增主键
	MODEL_ID VARCHAR2(30) NOT NULL, --绑定的模型ID
	DATA_ID VARCHAR2(20) NOT NULL, --对应的数据ID
	PRJ_ID VARCHAR2(20) NOT NULL, --对应的数据ID
	PRJ_MODEL_ID VARCHAR2(30) NOT NULL, --项目模型ID
	constraint PK_FLOW_DATA_RELATION primary key (ID)
);

alter table COLLAB_FUNCTION add (ICON_CLS VARCHAR2(400));