CREATE TABLE CWM_FAILED_MSG (
	ID VARCHAR2(20) NOT NULL,
	ERROR_CODE VARCHAR2(20),
	ERROR_TEXT VARCHAR2(50),
	SEND_TIME TIMESTAMP,
	MESSAGE_BODY BLOB,
	CORRELATION VARCHAR2(32),
	constraint PK_CWM_FAILED_MSG primary key (ID)
);

CREATE TABLE "CWM_MSG" (
"ID" VARCHAR2(38) NOT NULL ,
"TITLE" VARCHAR2(255) NULL ,
"CONTENT" VARCHAR2(4000) NULL ,
"TIMESTAMP" VARCHAR2(38) NULL ,
"USER_ID" VARCHAR2(38) NULL ,
"TYPE" VARCHAR2(10) NULL ,
"SRC" VARCHAR2(100) NULL ,
"DEST" VARCHAR2(100) NULL ,
"READED" VARCHAR2(2) NULL ,
PRIMARY KEY ("ID")
);