/*==============================================================*/
/* DBMS name:      ORACLE Version 10gR2                         */
/* Created on:     2016/3/10 ������ 11:12:32                       */
/*==============================================================*/
CREATE SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1 START WITH 2 NOMAXVALUE NOMINVALUE NOCYCLE  CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_TOOLS_GROUP INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_JBPM4_COUNTERSIGN_INFO INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_JBPM4_FLOW_BRANCH_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_JBPM4_RDM_COURSE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_JBPM4_FLOW_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_JBPM4_RDM_TASK_VAR INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_JBPM4_RDM_PARAMMAPPING INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_COMPONENT INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_COMPONENT_RELATIONDATA INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_PROJECT_MODEL_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_JBPM4_OPINION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_AUDIT_FLOW_MODEL_BIND INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_AUDIT_FLOW_DATA_BIND INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_AUDIT_FLOW_DATA_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;



CREATE SEQUENCE SEQ_CWM_ARITH_ATTRIBUTE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_ARITH_VIEW_CANSHUXIANG INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_CONS_EXPRESSION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_ENUM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_RELATION_COLUMNS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_RELATION_DATA INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_RELATION_TABLE_ENUM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_RESTRICTION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SCHEMA INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SEQGENERATOR INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TAB_COLUMNS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TABLE_COLUMN INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TABLE_ENUM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TABLES INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_VIEW_PAIXU_COLUMN INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_VIEW_RELATIONTABLE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_VIEW_RETURN_COLUMN INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_VIEWS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_DYNAMIC_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;


CREATE SEQUENCE SEQ_CWM_ETL_JOB INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_ETL_LOG INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_ETL_SCRIPT INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_ETL_TRANSLATOR INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_PARTITION_REMARK INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_DYNAMIC_TBOM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_RELATION_TBOM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TBOM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TBOM_DIR INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TBOM_FILE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_ALARM_INFO INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_ALARM_NOTICE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_ALARM_USER INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_ALARM_USER_HIST INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_ARITHMETIC INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_BACK INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_CODETONAME INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_PORTAL INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_REOPRT_BOOKMARK INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_REPORT_ITEMS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_REPORTS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_STATISTIC_CONFIG INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_ACCOUNT_STRATEGY INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_DEPARTMENT INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_FUNCTION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_LOG INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_OPERATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_OVERALLOPERATONS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_PARAMETER INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_PARTOPERATIONS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_PASSWORD_HISTORY INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_ROLE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE SEQ_CWM_SYS_ROLE_ARITH INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_ROLE_FUNCTION_TBOM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_ROLE_SCHEMA INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_ROLE_USER INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_TOOLS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_TOOLS_COLUMNS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_USER INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_USER_COLUMNS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_USER_DEPT INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_USER_ENUM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_USERLOGINHISTORY INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_TIME_INFO INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_USER_TOOL INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_USER_VIEW INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_FREEMARK_TEMPLATE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_MODEL_BTN_TYPE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_MODEL_BTN_INSTANCE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_MODEL_COLUMN_RULE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_MODEL_FORM_VIEW INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_MODEL_GRID_VIEW INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_MODEL_QUERY INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_ODS_FILE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_HADOOP_FILE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_USER_LINK INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_USER_PORTAL INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_ROLE_PORTAL INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_SYS_CHECKMODELSET INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE SEQ_CWM_DOC_HANDLER INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_DOC_COLUMN_SCOPE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_DOC_REPORTS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_DOC_REPORT_ITEMS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;


CREATE SEQUENCE SEQ_CWM_DATARELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_FILE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_FILE_GROUP INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_FILE_GROUP_ITEM INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_CWM_FOLDER INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;

--collab 2016 sequence
CREATE SEQUENCE SEQ_FLOW_DATA_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_TASK_DATA_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_HIST_FLOW_DATA_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_HIST_TASK_DATA_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_ROLE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_FUNCTION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_ROLE_FUNCTION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_ROLE_USER INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_DATA_FLOW_REL_SETTING INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_NOTICE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_TEMPLATE INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_FLOW_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_DATA_FLOW INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_JOB_CARVEPOS INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_DATATASK INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE SEQ_COLLAB_PRJ_MODEL_RELATION INCREMENT BY 1 START WITH 100 NOMAXVALUE NOMINVALUE NOCYCLE CACHE 20 NOORDER ;



--Orient_TaskData
CREATE SEQUENCE seq_order START WITH 500 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_DATATYPE START WITH 7 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_DATASUBTYPE START WITH 500 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_DATASUBTYPE START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_DATAOBJECT START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_DATAOBJECT_OLDVERSION START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;



--Orient_PVMTable
CREATE SEQUENCE SEQ_CWM_TASKCHECKMODEL START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_CHECKMODELDATATEMPLATE START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_TASKCHECKRELATION START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_TASKCHECK_HTML START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_TASKMULTIPLECHECKMODEL START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_TASKMULCHECKRELATION START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

--Orient_MQ
CREATE SEQUENCE SEQ_FAILED_MSG  START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CWM_MSG  START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;