CREATE TABLE WB_VAR
(
  VAR_ID     VARCHAR2(12 BYTE)                  NOT NULL,
  PARENT_ID  VARCHAR2(12 BYTE)                  NOT NULL,
  VAR_NAME   VARCHAR2(50 BYTE)                  NOT NULL,
  VAR_VALUE  VARCHAR2(255 BYTE),
  IS_VAR     NUMBER(1)
);



CREATE TABLE WB_VALUE
(
  VAL_ID       VARCHAR2(200 BYTE)               NOT NULL,
  VAL_CONTENT  VARCHAR2(255 BYTE)
);


CREATE TABLE WB_USER_ROLE
(
  USER_ID  VARCHAR2(12 BYTE)                    NOT NULL,
  ROLE_ID  VARCHAR2(12 BYTE)                    NOT NULL
);


CREATE TABLE WB_USER
(
  USER_ID       VARCHAR2(12 BYTE)               NOT NULL,
  USER_NAME     VARCHAR2(50 BYTE)               NOT NULL,
  DISPLAY_NAME  VARCHAR2(100 BYTE)              NOT NULL,
  PASSWORD      VARCHAR2(32 BYTE)               NOT NULL,
  STATUS        NUMBER(1)                       NOT NULL,
  CREATE_DATE   DATE                            NOT NULL,
  LOGIN_TIMES   NUMBER(9)                       NOT NULL,
  EMAIL         VARCHAR2(100 BYTE),
  USE_LANG      VARCHAR2(10 BYTE),
  LAST_LOGIN    DATE
);


CREATE TABLE WB_LOG
(
  LOG_DATE   DATE                               NOT NULL,
  USER_NAME  VARCHAR2(50 BYTE)                  NOT NULL,
  IP         VARCHAR2(50 BYTE)                  NOT NULL,
  LOG_TYPE   NUMBER(1)                          NOT NULL,
  MSG        VARCHAR2(255 BYTE)                 NOT NULL
);


CREATE TABLE WB_KEY
(
  KEY_ID     VARCHAR2(12 BYTE)                  NOT NULL,
  KEY_TYPE   VARCHAR2(50 BYTE)                  NOT NULL,
  KEY_NAME   VARCHAR2(50 BYTE)                  NOT NULL,
  KEY_VALUE  VARCHAR2(200 BYTE)                 NOT NULL
);


CREATE TABLE WB_DUAL
(
  DMY  NUMBER(1)
);


CREATE TABLE WB_CUST
(
  CUST_ID       VARCHAR2(12 BYTE)               NOT NULL,
  CUST_NO       VARCHAR2(5 BYTE)                NOT NULL,
  COMPANY       VARCHAR2(50 BYTE),
  ADDR          VARCHAR2(50 BYTE),
  COUNTRY       VARCHAR2(20 BYTE),
  TAX_RATE      NUMBER(6,2),
  INVOICE_DATE  DATE,
  REMARK        CLOB
);


CREATE TABLE WB_BBS_TITLE
(
  BBS_ID       VARCHAR2(12 BYTE)                NOT NULL,
  TITLE        VARCHAR2(255 BYTE)               NOT NULL,
  SET_TOP      NUMBER(1)                        NOT NULL,
  CREATE_DATE  DATE                             NOT NULL,
  CREATE_USER  VARCHAR2(12 BYTE)                NOT NULL,
  REPLY_COUNT  NUMBER(8)                        NOT NULL,
  VIEW_COUNT   NUMBER(8)                        NOT NULL,
  POST_DATE    DATE                             NOT NULL,
  POST_USER    VARCHAR2(12 BYTE)                NOT NULL,
  CONTENT      CLOB
);


CREATE TABLE WB_BBS_POST
(
  BBS_ID     VARCHAR2(12 BYTE)                  NOT NULL,
  POST_DATE  DATE                               NOT NULL,
  POST_USER  VARCHAR2(12 BYTE)                  NOT NULL,
  POST_ID    VARCHAR2(12 BYTE)                  NOT NULL,
  CONTENT    CLOB
);


CREATE TABLE WB_BBS_FILE
(
  FILE_ID       VARCHAR2(12 BYTE)               NOT NULL,
  CREATE_DATE   DATE                            NOT NULL,
  FILE_NAME     VARCHAR2(255 BYTE)              NOT NULL,
  FILE_SIZE     NUMBER(10)                      NOT NULL,
  FILE_CONTENT  BLOB
);


CREATE TABLE WB_TASK
(
  TASK_ID           VARCHAR2(12 BYTE)           NOT NULL,
  TASK_NAME         VARCHAR2(100 BYTE)          NOT NULL,
  INTERVAL_TYPE     NUMBER(1)                   NOT NULL,
  INTERVAL_EXPRESS  VARCHAR2(10 BYTE)           NOT NULL,
  CLASS_NAME        VARCHAR2(255 BYTE)          NOT NULL,
  BEGIN_DATE        DATE,
  END_DATE          DATE,
  STATUS            NUMBER(1)                   NOT NULL,
  REMARK            VARCHAR2(255 BYTE)
);


CREATE TABLE WB_SYSINFO
(
  RCV_DATE   DATE                               NOT NULL,
  SYS_TITLE  VARCHAR2(200 BYTE),
  SYS_IP     VARCHAR2(50 BYTE),
  SYS_SN     VARCHAR2(20 BYTE),
  SYS_CTX    VARCHAR2(200 BYTE)
);


CREATE TABLE WB_SALE
(
  RCV_DATE         DATE                         NOT NULL,
  TXN_ID           VARCHAR2(20 BYTE)            NOT NULL,
  PAYER_EMAIL      VARCHAR2(127 BYTE),
  MC_GROSS         NUMBER(9,2),
  MC_FEE           NUMBER(9,2),
  MC_CURRENCY      VARCHAR2(10 BYTE),
  FIRST_NAME       VARCHAR2(64 BYTE),
  LAST_NAME        VARCHAR2(64 BYTE),
  PAYMENT_DATE     VARCHAR2(50 BYTE),
  ADDRESS_COUNTRY  VARCHAR2(64 BYTE),
  ADDRESS_STATE    VARCHAR2(40 BYTE),
  ADDRESS_CITY     VARCHAR2(40 BYTE),
  ADDRESS_STREET   VARCHAR2(200 BYTE),
  ITEM_NAME        VARCHAR2(127 BYTE),
  RECEIVER_EMAIL   VARCHAR2(127 BYTE),
  REG_CODE         VARCHAR2(20 BYTE),
  USER_COUNT       NUMBER(7),
  OPT_SUPPORT      NUMBER(1)
);


CREATE TABLE WB_ROLE
(
  ROLE_ID    VARCHAR2(12 BYTE)                  NOT NULL,
  PARENT_ID  VARCHAR2(12 BYTE)                  NOT NULL,
  ROLE_NAME  VARCHAR2(50 BYTE)                  NOT NULL
);


CREATE TABLE WB_RESOURCE
(
  RES_ID       VARCHAR2(200 BYTE)               NOT NULL,
  RES_CONTENT  BLOB
);


CREATE TABLE WB_MODULE_ROLE
(
  MODULE_ID  VARCHAR2(12 BYTE)                  NOT NULL,
  ROLE_ID    VARCHAR2(12 BYTE)                  NOT NULL
);


CREATE TABLE WB_MODULE_HIS
(
  HIS_TITLE         VARCHAR2(100 BYTE)          NOT NULL,
  MODULE_ID         VARCHAR2(12 BYTE)           NOT NULL,
  PARENT_ID         VARCHAR2(12 BYTE)           NOT NULL,
  MODULE_CONTENT    CLOB,
  DISPLAY_NAME      VARCHAR2(255 BYTE),
  DISPLAY_ICON      VARCHAR2(50 BYTE),
  IS_HIDDEN         NUMBER(1),
  NEW_WIN           NUMBER(1),
  CREATE_USER       VARCHAR2(12 BYTE),
  CREATE_DATE       DATE,
  LAST_MODIFY_USER  VARCHAR2(12 BYTE),
  LAST_MODIFY_DATE  DATE,
  ORDER_INDEX       NUMBER(8)
);


CREATE TABLE WB_MODULE
(
  MODULE_ID         VARCHAR2(12 BYTE)           NOT NULL,
  PARENT_ID         VARCHAR2(12 BYTE)           NOT NULL,
  MODULE_CONTENT    CLOB,
  DISPLAY_NAME      VARCHAR2(255 BYTE),
  DISPLAY_ICON      VARCHAR2(50 BYTE),
  IS_HIDDEN         NUMBER(1),
  NEW_WIN           NUMBER(1),
  CREATE_USER       VARCHAR2(12 BYTE),
  CREATE_DATE       DATE,
  LAST_MODIFY_USER  VARCHAR2(12 BYTE),
  LAST_MODIFY_DATE  DATE,
  ORDER_INDEX       NUMBER(8)
);


CREATE TABLE WB_META
(
  META_NAME     VARCHAR2(30 BYTE)               NOT NULL,
  META_TYPE     VARCHAR2(50 BYTE)               NOT NULL,
  META_CONTENT  CLOB                            NOT NULL,
  ORDER_INDEX   NUMBER(6)                       NOT NULL
);


CREATE INDEX WB_BBS_POST_IDX1 ON WB_BBS_POST
(BBS_ID, POST_DATE);


CREATE INDEX WB_BBS_POST_IDX2 ON WB_BBS_POST
(POST_USER);


CREATE INDEX WB_BBS_TITLE_IDX1 ON WB_BBS_TITLE
(SET_TOP, POST_DATE);


CREATE INDEX WB_BBS_TITLE_IDX2 ON WB_BBS_TITLE
(CREATE_USER);


CREATE INDEX WB_BBS_TITLE_IDX3 ON WB_BBS_TITLE
(POST_USER);


CREATE INDEX WB_KEY_IDX ON WB_KEY
(KEY_TYPE);


CREATE INDEX WB_LOG_IDX ON WB_LOG
(LOG_DATE);


CREATE INDEX WB_META_IDX ON WB_META
(ORDER_INDEX);


CREATE INDEX WB_MODULE_IDX ON WB_MODULE
(PARENT_ID, ORDER_INDEX);


CREATE INDEX WB_MODULE_HIS_IDX ON WB_MODULE_HIS
(HIS_TITLE);


CREATE INDEX WB_MODULE_ROLE_IDX ON WB_MODULE_ROLE
(MODULE_ID);


CREATE INDEX WB_SALE_IDX1 ON WB_SALE
(RCV_DATE);


CREATE INDEX WB_SALE_IDX2 ON WB_SALE
(REG_CODE);


CREATE INDEX WB_SYSINFO_IDX ON WB_SYSINFO
(RCV_DATE);


CREATE UNIQUE INDEX WB_USER_UNQ ON WB_USER
(USER_NAME);


CREATE INDEX WB_USER_IDX ON WB_USER
(STATUS);


CREATE INDEX WB_USER_ROLE_IDX ON WB_USER_ROLE
(USER_ID);


ALTER TABLE WB_VAR ADD (
  PRIMARY KEY
 (VAR_ID));

ALTER TABLE WB_VALUE ADD (
  PRIMARY KEY
 (VAL_ID));

ALTER TABLE WB_USER ADD (
  PRIMARY KEY
 (USER_ID));

ALTER TABLE WB_KEY ADD (
  PRIMARY KEY
 (KEY_ID));

ALTER TABLE WB_CUST ADD (
  PRIMARY KEY
 (CUST_ID));

ALTER TABLE WB_BBS_TITLE ADD (
  PRIMARY KEY
 (BBS_ID));

ALTER TABLE WB_BBS_FILE ADD (
  PRIMARY KEY
 (FILE_ID));

ALTER TABLE WB_TASK ADD (
  PRIMARY KEY
 (TASK_ID));

ALTER TABLE WB_ROLE ADD (
  PRIMARY KEY
 (ROLE_ID));

ALTER TABLE WB_RESOURCE ADD (
  PRIMARY KEY
 (RES_ID));

ALTER TABLE WB_MODULE ADD (
  PRIMARY KEY
 (MODULE_ID));

ALTER TABLE WB_META ADD (
  PRIMARY KEY
 (META_NAME));

