--schemaId 322 
INSERT INTO PRJ_FOLDER_322 (ID, NAME_342, PRJ_FOLDER_322_ID) values (-1, '根文件夹', -2);

--the dependency between WBS work
CREATE TABLE WBS_WORK_DEPENDENCY ( 
	ID NUMBER(8) NOT NULL,    -- 自增主键
	ROOT_ID  VARCHAR2(20), --the root project id
	FROM_ID VARCHAR2(20),
	TO_ID VARCHAR2(20),
	DEPENDENCY_TYPE NUMBER(4) DEFAULT 0 NOT NULL    -- 依赖类型
);

CREATE SEQUENCE SEQ_WBS_WORK_DEPENDENCY
  START WITH 7
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

--the WBS work notice
CREATE TABLE WBS_WORK_NOTICE ( 
	ID NUMBER(8) NOT NULL,    -- 自增主键
	MODEL_NAME VARCHAR2(30),
	DATA_ID VARCHAR2(20),
	SCHEMA_ID VARCHAR2(20),
	USER_ID VARCHAR2(20),
	ROOT_ID VARCHAR2(20)
);

CREATE SEQUENCE SEQ_WBS_WORK_NOTICE
INCREMENT BY 1
START WITH 7
NOMAXVALUE
MINVALUE 0
NOCYCLE 
NOCACHE
NOORDER ;

--the audit flow-data relation
CREATE TABLE AUDIT_FLOW_DATA_RELATION ( 
	ID NUMBER(8) NOT NULL,    -- 自增主键
	AUDIT_TYPE VARCHAR2(30), --审批流程的详细类型
	TABLE_NAME VARCHAR2(20), --普通表则为表名，DS表则为MODEL_NAME(暂时认为只在一个schema下)
	DATA_ID VARCHAR2(20),
	PI_ID VARCHAR2(50),
	CREATE_TIME TIMESTAMP(6)
);

CREATE SEQUENCE SEQ_AUDIT_FLOW_DATA_RELATION
INCREMENT BY 1
START WITH 7
NOMAXVALUE
MINVALUE 0
NOCYCLE 
NOCACHE
NOORDER ;


--模型绑定审批流程定义
CREATE TABLE AUDIT_FLOW_MODEL_BIND ( 
  ID NUMBER(8) NOT NULL,    -- 自增主键
  SCHEMA_ID VARCHAR2(20),
  MODEL_NAME VARCHAR2(80),
  FLOW_NAME VARCHAR2(80),
  FLOW_VERSION VARCHAR2(20),
  AUDIT_FORM BLOB,
  USER_NAME VARCHAR2(20),
  LAST_UPDATE_DATE DATE
);

CREATE SEQUENCE SEQ_AUDIT_FLOW_MODEL_BIND
INCREMENT BY 1
START WITH 7
NOMAXVALUE
MINVALUE 0
NOCYCLE 
NOCACHE
NOORDER ;


--audit flow data bind
--暂时不使用，意图绑定协同任务，现在采用绑定模型
--cxk 20150907
--CREATE TABLE AUDIT_FLOW_DATA_BIND ( 
--	ID NUMBER(8) NOT NULL,    -- 自增主键
--	SCHEMA_ID VARCHAR2(20),
--	TABLE_NAME VARCHAR2(20), --普通表则为表名
--	DATA_ID VARCHAR2(20),
--	PD_ID VARCHAR2(50)
--);

--CREATE SEQUENCE SEQ_AUDIT_FLOW_DATA_BIND
--INCREMENT BY 1
--START WITH 7
--NOMAXVALUE
--MINVALUE 0
--NOCYCLE 
--NOCACHE
--NOORDER ;

--组件绑定
CREATE TABLE COMPONENT_TASK_DATA_BIND ( 
	ID NUMBER(8) NOT NULL,    -- 自增主键
	SCHEMA_ID VARCHAR2(20),
	TABLE_NAME VARCHAR2(20), --普通表则为表名
	DATA_ID VARCHAR2(20),
	COMPONENT_ID VARCHAR2(50)
);

CREATE SEQUENCE SEQ_COMPONENT_TASK_DATA_BIND
INCREMENT BY 1
START WITH 7
NOMAXVALUE
MINVALUE 0
NOCYCLE 
NOCACHE
NOORDER ;

CREATE TABLE CWM_STATISTIC_CONFIG ( 
  ID NUMBER(8) NOT NULL,    -- 自增主键
  CONFIG_NAME VARCHAR2(40),
  CONDITIONS VARCHAR2(200),  --统计条件
  SQLS VARCHAR2(1000),        --统计数据源准备
  SCRIPT VARCHAR2(1000),        --处理脚本
  REPORTCONFIG VARCHAR2(200),  --图形配置
  CONFIG_DESC VARCHAR2(100) --描述
);

CREATE SEQUENCE SEQ_CWM_STATISTIC_CONFIG
INCREMENT BY 1
START WITH 7
NOMAXVALUE
MINVALUE 0
NOCYCLE 
NOCACHE
NOORDER ;

--任务处理意见
CREATE TABLE JBPM4_OPINION(
  ID            VARCHAR2(38 BYTE),
  FLOWID        VARCHAR2(200 CHAR)              NOT NULL,
  ACTIVITY      VARCHAR2(200 CHAR)              NOT NULL,
  HANDLETIME    DATE                            NOT NULL,
  HANDLEUSER    VARCHAR2(38 BYTE)               NOT NULL,
  HANDLESTATUS  VARCHAR2(200 CHAR)              NOT NULL,
  LABEL         VARCHAR2(200 CHAR),
  VALUE         CLOB
);

CREATE SEQUENCE SEQ_JBPM4_OPINION
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 999999999999999999999999999
	CACHE 20
	NOCYCLE 
	NOORDER;
  
--the alarm
CREATE TABLE ALARM_INFO
(
  ID         VARCHAR2(30 CHAR),
  NLEVEL     NUMBER(2),
  CLASSNAME  VARCHAR2(100 CHAR),
  PARAMS     VARCHAR2(500 CHAR),
  ISALARM    NUMBER(1)                          DEFAULT 0
);

CREATE TABLE ALARM_CONTENT
(
  ID             VARCHAR2(300 CHAR),
  TITLE          VARCHAR2(200 CHAR),
  URL            VARCHAR2(200 BYTE),
  ALARM_INFO_ID  VARCHAR2(30 CHAR),
  CONTENT        CLOB
);
 
CREATE TABLE ALARM_NOTICE
(
  ID             VARCHAR2(30 CHAR),
  NOTICETYPE     NUMBER(8),
  TRIGGERTYPE    VARCHAR2(1 BYTE),
  INTERVAL       INTEGER,
  REPEAT         INTEGER,
  YEAR           VARCHAR2(4 BYTE),
  MONTH          VARCHAR2(2 BYTE),
  WEEKDAY        VARCHAR2(1 BYTE),
  TIME           VARCHAR2(10 BYTE),
  ALARM_INFO_ID  VARCHAR2(30 CHAR),
  MONTHDAY       VARCHAR2(2 BYTE)
);


CREATE TABLE ALARM_USER
(
  ALARMID  VARCHAR2(30 CHAR),
  USERID   VARCHAR2(30 CHAR),
  TYPE     NUMBER(1)
);


CREATE TABLE ALARM_INFO_HIST
(
  ID        VARCHAR2(30 CHAR),
  NLEVEL    NUMBER(10),
  TITLE     VARCHAR2(200 CHAR),
  URL       VARCHAR2(200 BYTE),
  SENDTIME  DATE,
  CONTENT   CLOB
);

CREATE TABLE ALARM_USER_HIST
(
  ALARMID  VARCHAR2(30 CHAR),
  USERID   VARCHAR2(30 CHAR),
  TYPE     NUMBER(1)
);


ALTER TABLE ALARM_INFO ADD (
  CONSTRAINT ALARM_INFO_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ALARM_CONTENT ADD (
  CONSTRAINT PK_CONTENT
 PRIMARY KEY
 (ID));
 
ALTER TABLE ALARM_CONTENT ADD (
  CONSTRAINT FK_CONTENT_INFO 
 FOREIGN KEY (ALARM_INFO_ID) 
 REFERENCES ALARM_INFO (ID));

 ALTER TABLE ALARM_CONTENT ADD (
  CONSTRAINT UN_CONTENT_INFO
 UNIQUE (ALARM_INFO_ID));
 
 ALTER TABLE ALARM_NOTICE ADD (
  PRIMARY KEY
 (ID));
 
 ALTER TABLE ALARM_NOTICE ADD (
  CONSTRAINT FK_NOTICE_INFO 
 FOREIGN KEY (ALARM_INFO_ID) 
 REFERENCES ALARM_INFO (ID));
 
 ALTER TABLE ALARM_NOTICE ADD (
  CONSTRAINT UN_NOTICE_INFO
 UNIQUE (ALARM_INFO_ID));
 
 ALTER TABLE ALARM_USER ADD (
  CONSTRAINT ALARM_USER_PK
 PRIMARY KEY
 (USERID, ALARMID));
 
 ALTER TABLE ALARM_USER ADD (
  CONSTRAINT FK_CWM_SYS_USER 
 FOREIGN KEY (USERID) 
 REFERENCES CWM_SYS_USER (ID));

 ALTER TABLE ALARM_USER ADD (
  CONSTRAINT FK_USER_INFO 
 FOREIGN KEY (ALARMID) 
 REFERENCES ALARM_INFO (ID));
 
ALTER TABLE ALARM_INFO_HIST ADD (
  CONSTRAINT ALARM_INFO_HIST_PK
 PRIMARY KEY
 (ID));
 
 ALTER TABLE ALARM_USER_HIST ADD (
  CONSTRAINT ALARM_USER_HIST_PK
 PRIMARY KEY
 (USERID, ALARMID));
 
 ALTER TABLE ALARM_USER_HIST ADD (
  CONSTRAINT FK_CWM_SYS_USER_HIST 
 FOREIGN KEY (USERID) 
 REFERENCES CWM_SYS_USER (ID));
 
 ALTER TABLE ALARM_USER_HIST ADD (
  CONSTRAINT FK_USER_INFO_HIST 
 FOREIGN KEY (ALARMID) 
 REFERENCES ALARM_INFO_HIST (ID));
 
 
 CREATE SEQUENCE SEQ_ALARM_INFO
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE SEQUENCE SEQ_ALARM_USER
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE SEQUENCE SEQ_ALARM_CONTENT
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;  

CREATE SEQUENCE SEQ_ALARM_NOTICE
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER; 
  
CREATE SEQUENCE SEQ_ALARM_INFO_HIST
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER; 

CREATE SEQUENCE SEQ_ALARM_USER_HIST
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
--data alter
alter table CWM_DATATYPE add BIND_PD_ID varchar2(20);
alter table AUDIT_FLOW_DATA_RELATION add FILTER varchar2(20);
	
